language: python
dist: xenial
python:
  - 3.7.2
env:
  matrix:
    - PROJ_NAME=raspi-cloud-controller MYPY_CMD="mypy --ignore-missing-imports -p cloud_flask"
    - PROJ_NAME=raspi-alexa-lambda     MYPY_CMD="mypy --ignore-missing-imports ."
install:
  - cd $PROJ_NAME
  - pip install mypy==0.650
  - pip install -r requirements.txt
script: "$MYPY_CMD"
jobs:
  include:
    - stage: build and deploy docker image; restart service
      env: STAGE=docker PROJ_NAME=raspi-cloud-controller
      if: type = api OR commit_message =~ concat('(', env(PROJ_NAME), ')')
      addons:
        ssh_known_hosts:
          secure: "Gv4OMxsA9buyRyg8SbtvjwF7lMmnFREXSGoAVzdTVy9QKoYtnZYC9q6VRaQtr10dpZS8w0RBQEKl/6KKebBbf81VtwONBXMANXJCageUPWpHHZ+uap9hEV42/88JdY00X2M5zZTfE5alnd1IcwLCMhN9Ky9dI9saUWv9q3NkakriTzDsZLYM/vFFLEQL7doj9WMgV7XqPanjjj00VGtbOYdVG6/2u2gSqA/EWSqrJlhaQ4wpNZSMhddDUL/LA76k+DvFAaCrbrRbvAYARY6YAJTkeCBmmJKHIkS/O5/5ZitNEX9ice0QP2JQ6TW15W2oZe1pllUggmy3djG7cnTdtTKmxI/IdLl8LBvIf+M5towxtux0I70U3DV0FctHmnDgpes9cMGZa0Lcg2b5WNf7K6hogUzY4mYlO8ys9Dh3ejJSIUWOvdC/IkqbKrG9wB0blbwxORoHZ701dcrkPXalhRyfIfJmIpuWS4EzgykoMeSqMplVmGfx63vcQO3R0L/SYEMxAjS2o+OlqeN0qEBYEX2Fbx0GA3yDQScdekn9l+kEH8ke7htJwK2XAtqSmE/y2dqf86IheqoBz98ddvLlvNtIn6yFGCv9muam4MGAImbeqnZQ0pa34qX0v28b7jnMMSGn6YnwtJ4sv0MVG7kTwKx56XUlbByYdoQLljI7lSw="
      install: skip
      before_script: cd $PROJ_NAME
      script:
        - docker build -t $DOCKER_USERNAME/$PROJ_NAME:latest .
        - docker tag $DOCKER_USERNAME/$PROJ_NAME:latest $DOCKER_USERNAME/$PROJ_NAME:travis-$TRAVIS_BUILD_NUMBER
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push $DOCKER_USERNAME/$PROJ_NAME
      after_success:
        - openssl aes-256-cbc -K $encrypted_0d630086225e_key -iv $encrypted_0d630086225e_iv -in ../.travis/travis_rsa.enc -out /tmp/travis_rsa -d
        - eval "$(ssh-agent -s)"
        - chmod 600 /tmp/travis_rsa
        - ssh-add /tmp/travis_rsa
        - ssh $SSH_USER@$SSH_HOST "sudo systemctl restart $PROJ_NAME.service"
    - stage: deploy lambda
      env: STAGE=lambda PROJ_NAME=raspi-alexa-lambda
      if: type = api OR commit_message =~ concat('(', env(PROJ_NAME), ')')
      install: skip
      before_script: cd $PROJ_NAME
      script: skip
      deploy:
        - provider: lambda
          function_name: "MyRaspberryPi-SmartHome-Lambda"
          region: "us-east-1"
          role: "arn:aws:iam::881012516071:role/MyRaspberryPi-Lambda"
          runtime: "python3.7"
          module_name: "lambda_function"
          handler_name: "lambda_handler"
          access_key_id:
            secure: "pLm5sDgr7zEww4OSwTCxltLpkvR1Fe2iWoGyRUJiZQX4yZpYlkjSX910wXl+ch0iQZ1C3QvbRaXJOMlwVEZ/q3Hh4I1oKrmGwb56PsWz39b0/piexitT7dAkpK3G5AX0+1sEYUYzwQRjrb4SrtnPRDky+m+NYcbVuGl1A3gVeMfUGEjieHxLQekqUhhQ4JXXwa+dB0av7e1+LkPS/uv/QzsPfgorlv2c2NDQuSLo+AzD+bA8Cbs+BB4Hv4ITVEV0nGqKmYuJxxbJR18DQpQTx0ICkwfZc9HkDtHvE1yCKiojPhjC7t5MzaJnyRwjspAw16QyBTpZlk/YF4NBLrg9Hb5BKvVyUxTcrU3BPLrkorI4F69RJAOB1qQkN59Rnr8wPNLM6EV0h862k8gbLHqoAKlT9H7TFddHbgHio7QROCs+1C8PX3+vvBne2YedvgC4fLLcY4TMg0J2E/VyiqTikq3umSo5ugiFZMFP5OOszrxH9YpSUUG4dv7pZW0o8Zbbkt+9K+XnYLrPbEQCgyM+ZHAT9l66A7/oIasrYE5xxcHsxSOuCGuYTlpsChJPthLt9XEWHz033AKGMWK4xePjlqlz3siW4EfqiYaRwRfJ+1P7rMEmV/yO5YlXfZOQbv+PXt2OR9sWcvMhXrickQxUEn7DLXwVnEuTeeYICSflcjo="
          secret_access_key:
            secure: "Xx6lZZegwrwMjTwBG3q8KxpGQWQOQtPz507wS4nZTWi0H2SJVImuSyzeTvlIs7+ITA0qP3RxOc0YSk9QDjKuIfadA+0IHRGyb5xDhr2X5lZ70lEA20cJJbMXmrcYSxmANe7eA5PSuWKEPzGG7ELum4+AFDQNfnmdTjjA05Kkw/MTZgpcuX1s1RUW3mGYKx+LJMCxgfC24nZRB2qNYXuzpk0MMJlvvHLGvvg8Ps22SQQ8yyy6NJG7s7me3BYu1rKdZr3oMMg7jXReajR2IgJxfg+V0YdinSXJSFLFY4hDsCASkBPFDdN3JcD91s+AU9W9bbj5wlU9q57Ec4fbA6hQ4QwuOgRrBH1O2EZlCpWq6YySmwfLJwTg/gltiDM4Rl+qgm6746UaH/2wjSee+Mzs1BcRh9czUv79oIuOAQ4hDEsY+LKveSJAT+yhHQmwr77BMAHa4nAwCIS+5/kbAnBLc9jsIXdKxHjUcnCuXGqRc4KeW7TAZgIEyxXqMPxsfGMlBhEMwTQxLhvxXDXb3qw02a//xsiPHDCh67Biu5MhWR8D9u6P4iTb9ozgQgrPk0nomhJOKwO5mQLWeLWHd8NkEduSwrx6V72zwvHKJWKiiCoyVfnOC3Hml4YBnzdNGKuO7qwG2NXft5MOUXVqfb9hgQJSAPZMqkmv6N+jkPXGUig="
        - provider: lambda
          function_name: "MyRaspberryPi-SmartHome-Lambda"
          region: "eu-west-1"
          role: "arn:aws:iam::881012516071:role/MyRaspberryPi-Lambda"
          runtime: "python3.7"
          module_name: "lambda_function"
          handler_name: "lambda_handler"
          access_key_id:
            secure: "pLm5sDgr7zEww4OSwTCxltLpkvR1Fe2iWoGyRUJiZQX4yZpYlkjSX910wXl+ch0iQZ1C3QvbRaXJOMlwVEZ/q3Hh4I1oKrmGwb56PsWz39b0/piexitT7dAkpK3G5AX0+1sEYUYzwQRjrb4SrtnPRDky+m+NYcbVuGl1A3gVeMfUGEjieHxLQekqUhhQ4JXXwa+dB0av7e1+LkPS/uv/QzsPfgorlv2c2NDQuSLo+AzD+bA8Cbs+BB4Hv4ITVEV0nGqKmYuJxxbJR18DQpQTx0ICkwfZc9HkDtHvE1yCKiojPhjC7t5MzaJnyRwjspAw16QyBTpZlk/YF4NBLrg9Hb5BKvVyUxTcrU3BPLrkorI4F69RJAOB1qQkN59Rnr8wPNLM6EV0h862k8gbLHqoAKlT9H7TFddHbgHio7QROCs+1C8PX3+vvBne2YedvgC4fLLcY4TMg0J2E/VyiqTikq3umSo5ugiFZMFP5OOszrxH9YpSUUG4dv7pZW0o8Zbbkt+9K+XnYLrPbEQCgyM+ZHAT9l66A7/oIasrYE5xxcHsxSOuCGuYTlpsChJPthLt9XEWHz033AKGMWK4xePjlqlz3siW4EfqiYaRwRfJ+1P7rMEmV/yO5YlXfZOQbv+PXt2OR9sWcvMhXrickQxUEn7DLXwVnEuTeeYICSflcjo="
          secret_access_key:
            secure: "Xx6lZZegwrwMjTwBG3q8KxpGQWQOQtPz507wS4nZTWi0H2SJVImuSyzeTvlIs7+ITA0qP3RxOc0YSk9QDjKuIfadA+0IHRGyb5xDhr2X5lZ70lEA20cJJbMXmrcYSxmANe7eA5PSuWKEPzGG7ELum4+AFDQNfnmdTjjA05Kkw/MTZgpcuX1s1RUW3mGYKx+LJMCxgfC24nZRB2qNYXuzpk0MMJlvvHLGvvg8Ps22SQQ8yyy6NJG7s7me3BYu1rKdZr3oMMg7jXReajR2IgJxfg+V0YdinSXJSFLFY4hDsCASkBPFDdN3JcD91s+AU9W9bbj5wlU9q57Ec4fbA6hQ4QwuOgRrBH1O2EZlCpWq6YySmwfLJwTg/gltiDM4Rl+qgm6746UaH/2wjSee+Mzs1BcRh9czUv79oIuOAQ4hDEsY+LKveSJAT+yhHQmwr77BMAHa4nAwCIS+5/kbAnBLc9jsIXdKxHjUcnCuXGqRc4KeW7TAZgIEyxXqMPxsfGMlBhEMwTQxLhvxXDXb3qw02a//xsiPHDCh67Biu5MhWR8D9u6P4iTb9ozgQgrPk0nomhJOKwO5mQLWeLWHd8NkEduSwrx6V72zwvHKJWKiiCoyVfnOC3Hml4YBnzdNGKuO7qwG2NXft5MOUXVqfb9hgQJSAPZMqkmv6N+jkPXGUig="
